config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wines, only: [:create, :edit, :update]
  resources :oenologists, only: [:create, :index, :new]
  
  root 'wines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magazine.rb
class Magazine < ApplicationRecord
    has_many :magazine_oenologists
    has_many :oenologists, through: :magazine_oenologists
end

app/models/magazine_oenologist.rb
class MagazineOenologist < ApplicationRecord
  belongs_to :magazine
  belongs_to :oenologist
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
    has_many :wine_oenologists
    has_many :wines, through: :wine_oenologists
    has_many :magazine_oenologists
    has_many :magazine, through: :magazine_oenologists
end

app/models/strain.rb
class Strain < ApplicationRecord    
    has_many :wine_strains
    has_many :wines, through: :wine_strains
    
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains
    has_many :wine_oenologists
    has_many :oenologists, through: :wine_oenologists
end

app/models/wine_oenologist.rb
class WineOenologist < ApplicationRecord
    belongs_to :wine
    belongs_to :oenologist
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
    belongs_to :strain
    belongs_to :wine
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
    before_action :authenticate_user!

    def index
        # @wines = Wine.all.includes([:strains, :wine_strains])
        @oenologists = Oenologist.all
        @oenologist = Oenologist.new
        @magazines = Magazine.all
    end
    
    def new
        @oenologist = Oenologist.new
    end
    
    def create
        @oenologist = Oenologist.new(name: oenologist_params[:name], age: oenologist_params[:age], nationality: oenologist_params[:nationality])

        oenologist_magazine = oenologist_params[:magazine_ids]
        oenologist_magazine.delete("") unless oenologist_magazine.nil?

        magazine_position = oenologist_params[:position]
        magazine_position.delete("") unless magazine_position.nil?

        for i in 0...(oenologist_magazine.count) do
            MagazineOenologist.create(oenologist_id: @oenologist.id, magazine_id: oenologist_magazine[i], position: magazine_position[i])
        end

        if @oenologist.save
            flash[:success] = "Oenologist successfully created"
            redirect_to root_path
        else
            flash[:error] = "Something went wrong"
            render 'new'
        end
    end
    
    private
    def oenologist_params
        params.require(:oenologist).permit(:name, :age, :nationality, magazine_ids: [],position: [])
    end
    
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
    before_action :authenticate_user!, except: :index

    def index
        @wines = Wine.all.includes([:strains, :wine_strains])
        @wine = Wine.new
        @strains = Strain.all.order(:name, :asc)
    end

    def create
        
        @wine = Wine.new(wine_params)
        
        strain_ids = params[:wine][:strain_ids]
        strain_ids.delete("") unless strain_ids.nil?

        strain_percents = params[:wine][:strain_percent]
        strain_percents.delete("") unless strain_percents.nil?

        begin

            Wine.transaction do
                @wine.save
                strain_ids.length.times do |i|
                    WineStrain.create(
                        wine_id: @wine.id,
                        strain_id: strain_ids[i],
                        percent: strain_percents[i]
                    )
                end

                flash[:success] = "Vino registrado exitosamente"
                redirect_to root_path
            end
        rescue
            flash[:error] = "El vino no se ha podido registrar"
            redirect_to root_path
        end
    end

    def edit
        @wine = Wine.find(params[:id])
    end

    def update
        @wine = Wine.find(params[:id])

        if @wine.update(name: wine_params[:name])

            percent = wine_params[:percent]
            percent.delete("") unless percent.nil?

            oenologist_ids = wine_params[:oenologist_ids]
            oenologist_ids.delete("") unless oenologist_ids.nil?

            score = wine_params[:score]
            score.delete("") unless score.nil?

            begin
                Wine.transaction do
                    @wine.save
                    oenologist_ids.length.times do |i|
                        WineOenologist.create(
                            wine_id: @wine.id,
                            oenologist_id: oenologist_ids[i],
                            score: score[i]
                        )
                    end
                    flash[:success] = "Evaluación registrada exitosamente"
                    redirect_to root_path
                end
            rescue
                flash[:error] = "La evaluación no se ha podido registrar"
                redirect_to root_path
            end
        end
    end

    private
    def wine_params
        params.require(:wine).permit(:name, strain_ids:[], percent:[], oenologist_ids:[], score:[])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinoTK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div class="container-fluid">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    
    </div>
    
    <%# <%=  render 'shared/footer' %>

  </body>
</html>

app/views/oenologists/index.html.erb
<div class="container mt-5">

    <h2>Nuevo Enólogo</h2>

    <%= form_with(model: @oenologist, local: true) do |f| %>

        <div class="border rounded bg-light p-3">
            <div class="mb-3">
                <%= f.text_field :name, placeholder:'Nombre', size:'50px' %>
            </div>

            <div class="mb-3">
                <%= f.number_field :age, placeholder:'Edad' %>
            </div>

            <div class="mb-3">
                <%= f.text_field :nationality, placeholder:'Nacionalidad', size:'50px' %>
            </div>
        </div>


        <div class="border rounded bg-light p-3 mt-3">
            <h3>Revistas</h3>
            <p class="text-info">Selecciona la revista y las posiciones del enólogo</p>
            <div class="field">
            <table class="table">
                <thead>
                    <th>Revista</th>
                    <th>Posición</th>
                </thead>

                <tbody>
                    <%= f.collection_check_boxes(:magazine_ids, Magazine.all, :id, :name) do |box| %>
                        <%= box.label class:"label-chechbox" do %>
                            <tr>
                                <td>
                                    <%= box.check_box + ' ' + box.text %>
                                </td>
                                <td>
                                    <span class="mr-3">
                                        <%= box.check_box + ' Editor' %>
                                    </span>
                                    <span class="mr-3">
                                        <%= box.check_box + ' Writer' %>
                                    </span>
                                    <span>
                                        <%= box.check_box + ' Reviewer' %>
                                    </span>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
            </div>
        </div>
        <div class="mt-3 mb-5">
            <%= f.submit 'Registrar Enólogo', class:'btn btn-primary' %>
        </div>
    <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="container-fluid footer p-3 mt-5">
    <h4 class="text-center text-white">VinoTK © 2021</h4>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top mb-5">
    <div class="container">
        <a class="navbar-brand" href="<%= root_path %>">La VinoTK de Peter</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= user_signed_in? ? "Bienvenido #{current_user.name}!" : 'Tu cuenta' %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <% if user_signed_in? %>
                            <% if current_user && current_user.admin? %>
                                <%= link_to 'Enólogos', oenologists_path, class:"dropdown-item" %>
                            <% end %>
                            <%= link_to  "Editar perfil", edit_user_registration_path, class:"dropdown-item" %>
                            <%= link_to  "Cerrar sesión", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                        <% else %>
                            <%= link_to  "Iniciar sesión", new_user_session_path, class:"dropdown-item" %>
                            <%= link_to  "Registrarse", new_user_registration_path, class:"dropdown-item" %>
                        <% end %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/wines/_wines.html.erb
<% if @wines.count > 0 %>

    <div class="container mb-5 border rounded bg-light mt-5">
        <h2 class="mt-4 mb-4 text-center">Listado de Vinos Disponibles</h2>

        <table class="table table-bordered bg-light">

            <thead class="table-primary">
                <tr class="text-center">
                    <th>Nombre</th>
                    <th>Cepas</th>
                    <% if current_user && current_user.admin? %>
                        <th>Enólogo / Puntaje</th>
                        <th>Anotar Puntaje</th>
                    <% end %>
                </tr>
            </thead>

            <tbody>
                <% @wines.each do |wine| %>
                    <tr>
                        <td><strong><%= wine.name %></strong></td>
                        <td>
                            <ul>
                                <% wine.wine_strains.each do |wine_strain| %>
                                    <li><%= wine_strain.strain.name %> (<%= wine_strain.percent %>%)</li>
                                <% end %>
                            </ul>
                        </td>
                        <% if current_user && current_user.admin? %>
                            <td>
                                <ul>
                                    <% wine.wine_oenologists.each do |wo| %>
                                        <p><%= wo.oenologist.name %> / <%= wo.score %> pts.</p>
                                    <% end %>
                                </ul>
                            </td>
                            <td><p class="text-center"><%= link_to '<i class="far fa-edit text-white btn btn-primary"></i>'.html_safe, edit_wine_path(wine) %></p></td>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>

        </table>
    </div>

<% else %>
    <div class="text-center mt-5">
        <h1>Bienvenido a la VinoTK</h1>
        <h3>Aún no hay vinos disponibles</h3>
    </div>
<% end %>

app/views/wines/edit.html.erb
<%= form_with(model: @wine, local: true) do |f| %>

    <div class="container rounded border bg-light p-3 mt-5">
        <div class="field">
            <h3>Nombre Vino</h3>
            <%= f.text_field :name %>
        </div>
    </div>

    <div class="container rounded border bg-light p-3 mt-3">
        <div class="field">
            <h3>Evaluación</h3>

            <table class="table">
                <thead>
                    <th>Nombre Enólogo</th>
                    <th>Evaluación</th>
                </thead>

                <tbody>
                    <%= f.collection_check_boxes(:oenologist_ids, Oenologist.all.order('age DESC'), :id, :name) do |box| %>
                        <%= box.label class:"label-chechbox" do %>
                            <tr>
                                <td>
                                    <%=box.check_box + ' ' + box.text %>
                                </td>
                                <td>
                                    <%= f.number_field '', min: 1, max: 10, name: 'wine[score][]' %>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>

    <div class="container p-3 mt-3">
        <div class="actions">
            <%= f.submit 'Actualizar Vino', class:'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/wines/index.html.erb
<% if current_user && current_user.admin? %>
    <div class="container">
        <div class="container border rounded bg-light p-3 mt-5">
            <h1 class="text-center mb-3">Registro de Nuevos Vinos</h1>

            <%= form_with(model: @wine, local: true) do |f| %>
                <div class="mb-3">
                    <span class="d-flex flex-row">
                        <div class="mr-3 mt-2">
                            <%= f.label 'Nombre' %>
                        </div>
                        <%= f.text_field :name, class:'form-control', size:'40' %>
                    </span>
                </div>
                
                <% if @strains.count > 0 %>

                    <p class="text-info">Selecciona la cepa en la columna de la izquierda e ingresa su porcentaje en la columna de la derecha.</p>
                    
                    <table class="table table-bordered">
                        <td><strong>Cepas Disponibles</strong></td>
                        <td><strong>Porcentaje Mezcla</strong></td>
                        <% @strains.each do |strain| %> 
                            <tr>
                                <td>
                                    <%= check_box(:wine, :strain_ids, {multiple: true}, strain.id, nil) %>
                                    <%= strain.name %>
                                </td>

                                <td>
                                    <input 
                                        type="number" 
                                        name="wine[strain_percent][]" 
                                        id="wine_strain_percent_<%= strain.id %>" 
                                        min="0"
                                        max="100"
                                        step="5"
                                        >
                                </td>
                            </tr>
                        <% end %>

                    </table>
                <% else %>
                    <h5> No hay cepas disponibles </h5>
                <% end %>

                <div class="mt-4">
                    <%= f.submit 'Guardar Vino', class:'btn btn-primary' %>
                </div>
            <%end%>
        </div>
    </div>
<% end %>

<div class="container mt-5">
    <%= render 'wines' %>
</div>

app/views/wines/newine.html.erb
<div class="border rounded bg-light p-3">
    <h1 class="text-center mb-3">Registro de Nuevos Vinos</h1>

    <%= form_with(model: @wine, local: true) do |f| %>
        <div class="mb-3">
            <span class="d-flex flex-row">
                <div class="mr-3 mt-2">
                    <%= f.label 'Nombre' %>
                </div>
                <%= f.text_field :name, class:'form-control', size:'40' %>
            </span>
        </div>
        
        <% if @strains.count > 0 %>

            <p>Sólo ingresa los porcentajes de los campos seleccionados</p>
            
            <table class="table table-bordered">

                <% @strains.each do |strain| %> 
                    <tr>
                        <td>
                            <%= check_box(:wine, :strain_ids, {multiple: true}, strain.id, nil) %>
                            <%= strain.name %>
                        </td>

                        <td>
                            <input 
                                type="number" 
                                name="wine[strain_percent][]" 
                                id="wine_strain_percent_<%= strain.id %>" 
                                min="0"
                                max="100"
                                step="5"
                                >
                        </td>
                    </tr>
                <% end %>

            </table>
        <% else %>
            <h5> No hay cepas disponibles </h5>
        <% end %>

        <div class="mt-4">
            <%= f.submit 'Guardar Vino' %>
        </div>
    <%end%>
</div>